In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [15]:
import numpy as np
arr=([[1,2,3],[4,5,6]])
newarr=np.array_split(arr,2)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [17]:
import numpy as np
arr=([[1,2,3],[4,5,6]])
newarr=np.array_split(arr,2)
print(newarr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [22]:
# Importing numpy as np
import numpy as np
A = np.array([[6, 1, 1],
[4, -2, 5],
[2, 8, 7]])
print("Rank of A:", np.linalg.matrix_rank(A))
print("\nTrace of A:", np.trace(A))
print("\nDeterminant of A:", np.linalg.det(A))
print("\nInverse of A:\n", np.linalg.inv(A))
print("\nMatrix A raised to power 3:\n",
np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]
